name: recmpox
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.9
  - minimap2
  - samtools
  - squirrel
  - iqtree=2.4.0
  - r-base
  - r-ape
  - r-phytools
  - bioconductor-ggtree
  - r-ggplot2
variables:
  PYTHONNOUSERSITE: "1"
